// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVs_Osn6kgxeXCtqzcphQBQ2loaRPZsoo',
    appId: '1:252334396153:android:f82aca6485ac148b678828',
    messagingSenderId: '252334396153',
    projectId: 'necta-test1-81f48',
    storageBucket: 'necta-test1-81f48.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChD93KxaNwBuWZFbLvnBCiArP-KUqn4aM',
    appId: '1:252334396153:web:d381bc427b50f3ae678828',
    messagingSenderId: '252334396153',
    projectId: 'necta-test1-81f48',
    authDomain: 'necta-test1-81f48.firebaseapp.com',
    storageBucket: 'necta-test1-81f48.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIAFHOKnM4ra13OQ2Z3sCdTNwswW-7q38',
    appId: '1:252334396153:ios:2c2681d0d531b84a678828',
    messagingSenderId: '252334396153',
    projectId: 'necta-test1-81f48',
    storageBucket: 'necta-test1-81f48.appspot.com',
    iosBundleId: 'com.aronfranco.nectaTest3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIAFHOKnM4ra13OQ2Z3sCdTNwswW-7q38',
    appId: '1:252334396153:ios:2c2681d0d531b84a678828',
    messagingSenderId: '252334396153',
    projectId: 'necta-test1-81f48',
    storageBucket: 'necta-test1-81f48.appspot.com',
    iosBundleId: 'com.aronfranco.nectaTest3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChD93KxaNwBuWZFbLvnBCiArP-KUqn4aM',
    appId: '1:252334396153:web:24fc6b22337f1142678828',
    messagingSenderId: '252334396153',
    projectId: 'necta-test1-81f48',
    authDomain: 'necta-test1-81f48.firebaseapp.com',
    storageBucket: 'necta-test1-81f48.appspot.com',
  );

}